/**
 * Untitled
 * Fast Healthcare Interoperability Resources (FHIR, pronounced \"Fire\") defines a set of \"Resources\" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR is designed for the web; the resources are based on simple XML or JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation.  
 *
 * OpenAPI spec version: unspecified
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountCoverage } from './accountCoverage';
import { AccountCoverage1 } from './accountCoverage1';
import { AccountIdentifier } from './accountIdentifier';
import { AccountMeta } from './accountMeta';
import { AccountServicePeriod } from './accountServicePeriod';
import { AccountSubject } from './accountSubject';
import { AccountText } from './accountText';
import { AccountType } from './accountType';


/**
 * 
 */
export interface Account { 
    resourceType: string;
    id: string;
    text: AccountText;
    identifier: Array<AccountIdentifier>;
    status: string;
    type: AccountType;
    name: string;
    subject: Array<AccountSubject>;
    servicePeriod: AccountServicePeriod;
    coverage: Array<AccountCoverage1>;
    owner: AccountCoverage;
    description: string;
    meta: AccountMeta;
}
