/**
 * Untitled
 * Fast Healthcare Interoperability Resources (FHIR, pronounced \"Fire\") defines a set of \"Resources\" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR is designed for the web; the resources are based on simple XML or JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation.  
 *
 * OpenAPI spec version: unspecified
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountCoverage } from './accountCoverage';
import { AccountIdentifier } from './accountIdentifier';
import { AccountMeta } from './accountMeta';
import { AccountText } from './accountText';
import { ClaimCareTeam } from './claimCareTeam';
import { ClaimDiagnosis } from './claimDiagnosis';
import { ClaimInsurance } from './claimInsurance';
import { ClaimItem } from './claimItem';
import { ClaimPayee } from './claimPayee';
import { ClaimPriority } from './claimPriority';
import { ClaimType } from './claimType';


/**
 * 
 */
export interface Claim { 
    resourceType: string;
    id: string;
    text: AccountText;
    identifier: Array<AccountIdentifier>;
    status: string;
    type: ClaimType;
    use: string;
    patient: AccountCoverage;
    created: string;
    insurer: AccountCoverage;
    provider: AccountCoverage;
    priority: ClaimPriority;
    payee: ClaimPayee;
    careTeam: Array<ClaimCareTeam>;
    diagnosis: Array<ClaimDiagnosis>;
    insurance: Array<ClaimInsurance>;
    item: Array<ClaimItem>;
    meta: AccountMeta;
}
